# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mydockerapp01

on:
  push:
    branches:
      - v1
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ea0135fb43c24cdab9f2f1be6da5fb27 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f78af8ead1d444a095457701a9877806 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ea0135fb43c24cdab9f2f1be6da5fb27 }}/delmenow:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mydockerapp01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_26223d50783746d2902fbb73df02635d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ea0135fb43c24cdab9f2f1be6da5fb27 }}/delmenow:${{ github.sha }}'